[global]
port = 8000

[debug]
public_root = "http://localhost:8000/"
root_domain = "localhost"
login_cookie_expiration = "1h"
enable_hash_password = true

[test]
public_root = "http://localhost:8000/"
root_domain = "localhost"
login_cookie_expiration = "30d"
enable_hash_password = true
users = []
secret_key = "00000000000000000000000000000000000000000000"

